/**
 * Copyright 2011-2015
 *
 * Modified from https://github.com/BoostGSoC13/boost.trie
 *
 * Distributed under the Boost Software License, Version 1.0.
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#ifndef LIBBITCOIN_TRIE_STRUCTURE_NODE_HPP
#define LIBBITCOIN_TRIE_STRUCTURE_NODE_HPP

#include <boost/utility.hpp>
#include <bitcoin/bitcoin.hpp>
#include <bitcoin/blockchain/tree/red_black_store.hpp>
#include <bitcoin/blockchain/trie/trie_value_node.hpp>

namespace libbitcoin {
namespace blockchain {

template <typename Key,
    typename Value,
    typename Comparer = std::greater<Key>>
class trie_structure_node : private boost::noncopyable
{
public:

    typedef Key key_type;
    typedef Value value_type;
    typedef Comparer comparer_type;

    typedef trie_structure_node<key_type, value_type, comparer_type> structure_node_type;

    typedef trie_value_node<value_type, structure_node_type> value_node_type;

    struct value_boundaries
    {
        value_node_type* leftmost;
        value_node_type* rightmost;
        value_node_type* head;
        value_node_type* tail;
    };

    typedef std::allocator<red_black_node<key_type, value_boundaries>> red_black_allocator_type;

    typedef red_black_store<key_type,
        value_boundaries,
        comparer_type,
        red_black_allocator_type> balanced_tree_store;

public:

    binary_type label;
    structure_node_type* parent;
    balanced_tree_store store;

public:

    trie_structure_node();

    trie_structure_node(red_black_allocator_type allocator);

    bool has_children() const;

    bool has_children(const key_type& key) const;

    bool has_value() const;

    bool has_value(const key_type& key) const;

    structure_node_type* get_child(bool matching_bit) const;

    void set_child(bool matching_bit, structure_node_type* node);

    structure_node_type* get_first_child() const;

    structure_node_type* get_first_child(const key_type& key) const;

    structure_node_type* get_last_child() const;

    structure_node_type* get_last_child(const key_type& key) const;

    bool remove_child(structure_node_type* child);

private:

    structure_node_type* children_[2];
};

} // namespace blockchain
} // namespace libbitcoin

#include <bitcoin/blockchain/impl/trie/trie_structure_node.ipp>

#endif
